#!/bin/bash


## Setup Dirs
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CD=$PWD
cd $DIR


## Setup initial apps
rpm -iUvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
yum update -y
yum install -y docker-io python-pip
pip install docker-py


## Setup nginx
bash other/nginx-ssl-setup.sh
iptables -I INPUT 5 -i eth0 -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -I INPUT 5 -i eth0 -p tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -I INPUT 5 -i eth0 -p tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT
service iptables save

## Build containers
bash DockerForge/build-containers-ngid.sh &
#bash DockerForge/build-containers.sh &


## Install Docker Startup
cat DockerStartup/dockerstartup.sh > /usr/bin/dockerstartup
chmod +x /usr/bin/dockerstartup
cat DockerStartup/dockerstartup.init > /etc/init.d/dockerstartup
chmod +x /etc/init.d/dockerstartup
cat DockerStartup/dockerstartup-persistant > /etc/dockerstartup-persistant
cat DockerStartup/dockerstartup > /etc/dockerstartup


## Install DockProx
mkdir -p /etc/dockprox
cp other/*.template /etc/dockprox/
cat DockProx.py > /usr/bin/dockprox
chmod +x /usr/bin/dockprox
cat other/dockprox.init > /etc/init.d/dockprox
chmod +x /etc/init.d/dockprox


## Setup services
chkconfig docker on
chkconfig dockerstartup on
chkconfig nginx on
chkconfig dockprox on
service docker restart
service dockerstartup restart
service nginx restart
service dockprox restart
